#!/bin/sh
"exec" "`dirname $0`/../ta/venv/bin/python" "$0" "$@"


import flask_assets
import sys
import json

if len(sys.argv) != 2:
    print('Usage: clean-json <json-file>')
    sys.exit(1)

fname = sys.argv[1]
with open(fname) as f:
    data = json.load(f)

with open(fname, 'w') as f:
    json.dump(data, f, indent=2, sort_keys=True)
