#!/bin/sh
"exec" "`dirname $0`/../ta/venv/bin/python" "$0" "$@"

import getpass
import json
import os
import prompts
import re
import subprocess
import sys
from prompts import toggle_prompt
from helpers import json_edit, line_read, locked_file
import tabulate
from config import CONFIG
from typing import Set, List

os.umask(0o007)

bl_path = os.path.join(CONFIG.base_path, 'ta/t-s-blocklist.json')
students_path = os.path.join(CONFIG.base_path, 'ta/groups/students.csv')

assert os.path.exists(bl_path), f'blocklist file {bl_path} does not exist'
assert os.path.exists(students_path), \
    f'student file {students_path} does not exist'

with locked_file(bl_path) as f:
    curr_bl = json.load(f)

ta_login = getpass.getuser()
assert prompts.yn_prompt(f'Confirm your username is {ta_login}')

curr_blocked = set(curr_bl.get(ta_login, []))

student_print = []
lines: List[List[str]] = line_read(students_path, delim=',')
students = []
for login, email, name in lines:
    if login in curr_blocked:
        continue

    students.append(login)
    student_print.append((login, name))


print()
print('Which student(s) would you like to blocklist?')
print('Type the number next to their login(s)')
print('(red = blocklisted; ctrl-c when you\'re done')

if not students:
    print('No students to blocklist')
else:
    to_blocklist = toggle_prompt(students,
                                 set(),
                                 [f'{r[0]} ({r[1]})' for r in student_print])

    with json_edit(bl_path) as data:
        data[ta_login] = list(curr_blocked | to_blocklist)

    print('\nBlocklist updated.')
