#!/bin/sh
"exec" "`dirname $0`/../ta/venv/bin/python" "$0" "$@"

import getpass
import json
import os
import prompts
import re
import subprocess
import sys
from helpers import json_edit, line_read
import tabulate
from config import CONFIG
from typing import Set, List

os.umask(0o007)

anon_path = os.path.join(CONFIG.base_path, 'ta/t-s-blocklist.json')
students_path = os.path.join(CONFIG.base_path, 'ta/groups/students.csv')

assert os.path.exists(anon_path), f'anon_path {anon_path} does not exist'

ta_login = getpass.getuser()
assert prompts.yn_prompt(f'Confirm your username is {ta_login}')

ls = []
lines: List[List[str]] = line_read(students_path, delim=',')
students = []
for i, (login, email, name) in enumerate(lines):
    students.append(login)
    ls.append([i + 1, login, name])

print(tabulate.tabulate(ls, headers=('#', 'Login', 'Name')))

to_blocklist: Set[str] = set()

print('')
print('Which user(s) would you like to blocklist?')
print('Type the number next to their login(s)')
print('(ctrl-c to stop)')

while True:
    inp = prompts.int_prompt(len(lines), '> ')
    if inp is None:
        # exited...
        break

    student = students[inp - 1]
    if prompts.yn_prompt(f'Confirm you want to blocklist {student}'):
        to_blocklist.add(student)
        msg = (
               f'{student} blocklisted... '
               f'Enter another number or ctrl-c to end'
              )
        print(msg)

with json_edit(anon_path) as data:
    if ta_login not in data:
        data[ta_login] = []

    data[ta_login] = list(set(data[ta_login]).union(to_blocklist))

print('\nBlocklist updated.')
