#!/course/cs0111/ta/grading/venv/bin/python2.7

import os
import subprocess
import re
import tabulate

BASE_PATH = '/course/cs0111'

lab_base = os.path.join(BASE_PATH, 'ta/grading/data/labs')

dirs = next(os.walk(lab_base))[1]
students_path = os.path.join(BASE_PATH, 'ta/groups', 'students.txt')
with open(students_path) as f:
    lines = map(str.strip, f.read().strip().split('\n'))

ls = []
for i, user in enumerate(lines):
    txt = subprocess.check_output(["ldapsearch", "-Q", "cn=%s" % user])
    res = re.search('gecos:(.*)', txt, re.MULTILINE)
    if res:
        full_name = res.group(1).strip().split(', ')[0]
    else:
        full_name = 'Not found'

    ls.append([i + 1, user, full_name])

print tabulate.tabulate(ls, headers=('#', 'Login', 'Name'))

print ''
print 'Who are you switching?'
print 'Type the number next to their login'
while True:
    inp = raw_input('Enter a number: ')
    try:
        student = lines[int(inp) - 1]
        print ''
        print 'Running lab switch for %s.' % student
        break
    except ValueError:
        print 'Enter a number only...'

print 'Temporary or permanent lab switch?'
print '1. Temporary'
print '2. Permanent'
while True:
    try:
        res = int(raw_input('> '))
        if not (res == 1 or res == 2):
            print 'Enter 1 or 2...'
            continue
        else:
            temp = res == 1
            break
    except ValueError:
        print 'Enter a number...'

if temp:
    print 'Which lab are you switching?'
    for i, d in enumerate(dirs):
        nice_name = '%s %s' % (d[0:3], int(d[3:]))
        print '%s. %s' % ((i + 1), nice_name)

    while True:
        try:
            res = int(raw_input('> '))
            if res not in range(1, 13):
                print 'Enter a valid number...'
                continue
            else:
                break
        except ValueError:
            print 'Enter a number...'

    gothrough = [res]
    print gothrough
else:
    gothrough = range(1, 13)

print 'Switch to which lab?'
print '\t1. Lab 1 (Thursday 11AM-1PM)'
print '\t2. Lab 2 (Thursday 2:30-4:30PM)'
print '\t3. Lab 3 (Thursday 6:00-8:00PM)'
print '\t4. Lab 4 (Friday 3:00-5:00PM)'
while True:
    try:
        res = int(raw_input('> '))
        if res not in range(1, 5):
            print 'Enter a valid number...'
        break
    except ValueError:
        print "Enter a number..."

for lab in gothrough:
    folder = 'lab%s' % str(lab).zfill(2)
    b = os.path.join(lab_base, folder)
    to_path = os.path.join(b, 'l%s-roster.txt' % res)

    for l in range(1, 5):
        p = os.path.join(b, 'l%s-roster.txt' % l)
        with open(p) as f:
            ss = map(str.strip, f.read().strip().split('\n'))

        if student in ss:
            ss.remove(student)
            with open(p, 'w') as f:
                f.write('\n'.join(ss))

    with open(to_path, 'a') as f:
        f.write('\n%s' % student)

s = ''
if temp:
     s += 'Lab %s switch' % gothrough[0]
else:
     s += 'Permenant lab switch'

s += ' for %s to session %s complete.' % (student, res)
print s
