#!/usr/bin/env bash

echo "Making override in current directory..."
cp report.txt report-override.txt
cp grade.json grade-override.json
echo "Override files created (grade-override.json, report-override.txt)."
