#!/usr/bin/env bash

printf '# Copy this into code.pyret.org/editor\n# Student code starts\n';
cat $2;
printf '\n# Student code ends\n# Start TA tests\n';
cat $1;
printf '\n'

# IMPL=$(readlink -f $1)
# TEST=$(readlink -f $2)
# OUTP=$(readlink -f $3)
# TESTP=$OUTP/tests.arr

# cd $OUTP
# echo $IMPL $TEST $OUTP | /home/jswrenn/projects/powder-monkey/evaluate/evaluate-many.sh &>/dev/null

# python /course/cs0050/tabin/print_results.py pyret $OUTP

