#!/usr/bin/env bash

IMPL=$(readlink -f $1)
TEST=$(readlink -f $2)
OUTP=$(readlink -f $3)
TESTP=$OUTP/tests.arr

cd $OUTP

echo $IMPL $TEST $OUTP | /home/jswrenn/projects/powder-monkey/evaluate/evaluate-many.sh &>/dev/null

python /course/cs0111/tabin/print_results.py pyret $OUTP

