#!/usr/bin/env python

import sys
import os
import subprocess
import json

if len(sys.argv) != 5:
    print "Usage: run-tests <pyret/python> <student-file> <test-file> <output-dir>"
    sys.exit(1)

if sys.argv[1] == "python":
    print "Not implemented yet"
    sys.exit(1)
elif sys.argv[1] != "pyret":
    print "Usage: run-tests <pyret/python> <student-file> <test-file> <output-dir>"
    sys.exit(1)

if not os.path.isabs(sys.argv[2]):
    print 'Student file must be an absolute path'
    sys.exit(1)
elif not os.path.isabs(sys.argv[3]):
    print 'Test file must be an absolute path'
    sys.exit(1)

if not os.path.exists(sys.argv[2]):
    print 'Student file does not exist'
    sys.exit(1)
elif not os.path.exists(sys.argv[3]):
    print 'Test file does not exist'
    sys.exit(1)

cmd = ['/home/jswrenn/projects/powder-monkey/evaluate/evaluate-many.sh']
ps = subprocess.Popen(["echo", sys.argv[2], sys.argv[3],
                       sys.argv[4]], stdout=subprocess.PIPE)
output = subprocess.check_output(cmd, stdin=ps.stdout,
                                 stderr=open('/dev/null', 'w'))
ps.wait()

res_path = os.path.join(sys.argv[4], 'results.json')
with open(res_path) as f:
    print json.load(f)

