#!/usr/bin/env bash
echo "Use asgn = HTA_Assignment(\"Homework x\") to create an assignment!"
echo "Type asgn.<press tab> to see options for the assignment object! This works for all objects."
echo "Type asgn.method_name?<press enter> to see information about how to use a method."
echo "this works for all methods/functions."

umask 007
/course/cs0050/ta/venv/bin/ipython -i /course/cs0050/hta/grading/hta_classes.py
