#!/usr/bin/env python
import os
import shutil

data_path = '/course/cs0111/ta/assignments.json'
base_path = '/course/cs0111/hta/asgn-backups'

fs = os.listdir(base_path)
m = -1
for f in fs:
    try:
        n = int(f.split('-')[0])
    except ValueError:
        continue
    except IndexError:
        continue

    m = max(n, m)

new = m + 1
newpath = '/course/cs0111/hta/asgn-backups/%s-assignments.json' % new
shutil.copy(data_path, newpath)
