#!/usr/bin/env bash
execDir=$(dirname "$0" | xargs realpath);
pyBin=$(echo "$execDir/../ta/venv/bin" | xargs realpath);
umask 007;

lockfile -5 -r 3 "$execDir/../hta/handin/handin-lock.lock" || exit 1;
cd "$execDir/../hta/handin";
"$pyBin/python" "$execDir/../hta/handin/check_submissions.py"
rm -f "$execDir/../hta/handin/handin-lock.lock"
