#!/bin/bash
BASE=`realpath "$(dirname $0)/.."`
BACKUPPATH=${BASE}/hta/data_backups;
cd $BASE;

if [[ $1 ]]; then
    fname=$1;
else
    fname=$(echo `date +%Y-%m-%d_%H-%M-%S`.zip);
fi;

dest=${BACKUPPATH}/${fname};

if [[ -e $dest ]]; then
    echo "backup $1 already exists."
    read -p "continue? [y/n]: " cont;
    [ $cont == "y" ] || exit;
fi;

dirs=`echo ta/config.py ta/assignments.json ta/t-s-blocklist.json hta/s-t-blocklist.json hta/grading/anonymization ta/grading/grades ta/grading/data hta/summaries hta/handin/students hta/grades hta/groups`
zip -qr $dest $dirs -x *.gitignore* -x *__pycache__* 2&>stderr.log;
[ $(wc -l <stderr.log) -gt 100 ] && echo over 100 permission denied errors while running zip command;
[ -e stderr.log ] && rm stderr.log;
echo "backup to $fname complete.";
