#!/usr/bin/env bash
umask 007
echo running
lockfile -5 -r 3 /course/cs0111/hta/handin/handin-lock.lock || exit 1
echo lock acquired
cd /course/cs0111/hta/handin
/course/cs0111/ta/venv/bin/python /course/cs0111/hta/handin/check_submissions.py
echo script complete
rm -f /course/cs0111/hta/handin/handin-lock.lock
echo lock released
