#!/usr/bin/env bash
lockfile -r 0 /course/cs0111/hta/handin/handin-lock.lock || exit 1
umask 007
cd /course/cs0111/hta/handin
/course/cs0111/hta/handin/v3/bin/python3.7 /course/cs0111/hta/handin/check_submissions.py
rm -f /course/cs0111/hta/handin/handin-lock.lock
