#!/bin/sh
"exec" "`dirname $0`/../ta/venv/bin/python" "$0" "$@";

import sys
import getpass
from passlib.hash import sha256_crypt

from helpers import locked_file, BASE_PATH, pjoin

print('')

print('This script will reset the password required to log in to the')
print('grading app. It uses sha256 encryption. the hash will be stored')
print('in /ta/grading. be careful not to commit the hash to git')

print('')

password_r1 = getpass.getpass('New password to use: ')
password_r2 = getpass.getpass('Re-enter password: ')

if password_r1 != password_r2:
    print('Passwords do not match, try again.')
    sys.exit(1)

if len(password_r1) < 5:
    print('Password must be >= 5 characters')
    sys.exit(1)

pass_hash = sha256_crypt.hash(password_r2)
hash_path = pjoin(BASE_PATH, 'ta/grading/passwd_hash.txt')
with locked_file(hash_path, 'w') as f:
    f.write(pass_hash)

print('Done.')