#!/usr/bin/env python

# Notes: 
#  - if running from ssh/fastx, make sure to run "kinit" first
# 
# @author zkirsche Aug 2018
# edited by eberkowi Aug 2018
#   - reduced terminal output
#   - reorganized functions to take group names instead of login CSV files

import cgi
import csv
from StringIO import StringIO
import re
import os
import smtplib
import subprocess
import sys

if len(sys.argv) != 4:
    print 'Usage: group-data <group> <csv | txt> <path-to-output>'
    sys.exit(1)

csv = sys.argv[2] == 'csv'

def login_to_email(login):
    '''
    Input: the brown cs login to query
    Output: the brown email, or an error string that the email can't be found
            and a boolaen indicating if the search succeeded
    '''
    try:
        login = login.lower().strip()
        userdata = subprocess.check_output(["ldapsearch", "-Q", "cn=" + login])
        ldap_email = re.search("mail:(.*)", userdata, re.MULTILINE)
        if ldap_email:
            email = ldap_email.group(1).strip()
            return email, True
        else:
            if login == 'qa0111':
                return 'elias_berkowitz@brown.edu', True
            else:
                return "Unknown login %s (email HTAs)" % login, False

    except subprocess.CalledProcessError:
        return "Warning: ldap search for %s failed" % login, False

def login_to_name(login):
    login = login.lower().strip()
    try:
        userdata = subprocess.check_output(['ldapsearch', '-Q', 'cn=' + login])
        ldap_name = re.search('gecos:(.*)', userdata, re.MULTILINE)
        if ldap_name:
            return ldap_name.group(1).strip().split(',')[0].strip(), True
        else:
            return 'No name for %s (email HTAs)' % login, False
    except:
        return 'Warning: ldap search for %s failed' % login, False

def get_logins_from_group(group_name):
    '''
    Input: a group name (i.e. cs-0111ta)
    Output: A list of the usernames of the members of that group 
    (uses the members command)

    repeated usernames are deleted
    '''
    cmd = ['better-members', group_name]
    sp = subprocess.Popen(cmd,
                          stdout=subprocess.PIPE,
                          stderr=subprocess.PIPE)
    out, err = sp.communicate()
    if out and not err:
        # success
        return out.strip().split(' ')
    elif not out and not err:
        # no members in group
        return []
    else:
        # probably invalid group name
        raise subprocess.CalledProcessError(1, cmd, err)

logins = get_logins_from_group(sys.argv[1])
if csv:
    data = []
    for login in logins:
        email = login_to_email(login)[0]
        name  = login_to_name(login)[0]
        data.append((login, email, name))
    
    S = ''
    for d in data:
        S += '%s,%s,%s\n' % (d[0], d[1], d[2])

    with open(sys.argv[3], 'w') as f:
        f.write(S)
else:
    S = ''
    for l in logins:
        S += '%s\n' % l
    with open(sys.argv[3], 'w') as f:
        f.write(S)


