#!/usr/bin/env bash
# lints all relevant python files
# should use after editing grading app code
baseDir=$(dirname "$0/.." | xargs realpath);
function linecount() {
    lc=`$baseDir/ta/venv/bin/python -c "print(len(open('$1').read().split('\n')))"`
}
cd $baseDir
cat $baseDir/lintfiles | while read p; do
    mypy $p --ignore-missing-imports;
done

lines=`cat $baseDir/lintfiles | python -c "import sys; fs = sys.stdin.read().strip().split('\n'); print(sum(map(lambda f: len(open(f).read().strip().split('\n')), fs)))"`
echo "$lines lines of code"
