#!/usr/bin/env bash
# lints all relevant python files
# should use after editing grading app code

function linecount() {
    lc=`/course/cs0050/ta/venv/bin/python -c "print(len(open('$1').read().split('\n')))"`
}
cd /course/cs0050
cat /course/cs0050/lintfiles | while read p; do
    mypy $p --ignore-missing-imports;
done

lines=`cat /course/cs0050/lintfiles | python -c "import sys; fs = sys.stdin.read().strip().split('\n'); print(sum(map(lambda f: len(open(f).read().strip().split('\n')), fs)))"`
echo "$lines lines of code"
