#!/usr/bin/env bash

# run this file to rewrite students.txt, students.csv, tas.txt, and htas.txt
# run when a student drops the course, for example. I'd recommend
# a crontab running this once a minute in the first few weeks of the
# semester so grading and handin scripts don't get messed up.
BASE_PATH="/course/cs0050/hta/groups"
PATH="/course/cs0050/htabin:$PATH"

function update-group() {
    P=$BASE_PATH/$3
    group-data $1 $2 $P
    hta-ta-file $P rx
}


update-group cs-0050student txt students.txt
update-group cs-0050student csv students.csv
update-group cs-0050hta txt htas.txt
update-group cs-0050ta txt tas.txt
