#!/usr/bin/env bash

# run this file to rewrite students.txt, students.csv, tas.txt, and htas.txt
# run when a student drops the course, for example. I'd recommend
# a crontab running this once a minute in the first few weeks of the
# semester so grading and handin scripts don't get messed up.
baseDir=$(dirname "$0/.." | xargs realpath);
BASE_PATH="$baseDir/hta/groups"
PATH="$PATH:$baseDir/htabin"

function update-group() {
    P=$BASE_PATH/$3
    group-data $1 $2 $P
    hta-ta-file $P rx
}


update-group cs-0111student txt students.txt
update-group cs-0111student csv students.csv
update-group cs-0111hta txt htas.txt
update-group cs-0111ta txt tas.txt
