#!/course/cs0111/ta/venv/bin/python

import os

from student_data import get_login_email_zip
from helpers import locked_file

base = '/course/cs0111'
csv_path = os.path.join(base, 'hta', 'groups', 'students.csv')

login_email_lst = get_login_email_zip('cs-0111student')
s = ''
for login, email in login_email_lst:
    s += f'{login},{email}\n'

with locked_file(csv_path, 'w') as f:
    f.write(s)
