#!/course/cs0111/ta/venv/bin/python

# don't move this script since it needs access to hta_classes.py

import sys

from hta_classes import *

if len(sys.argv) != 3:
    print('Usage: add-student-submission <assignment full name> <login>')
    sys.exit(1)

hw = HTA_Assignment(sys.argv[1])
hw.add_new_handin(sys.argv[2])
