#!/course/cs0111/ta/grading/venv/bin/python
import sys

from os.path import join as pjoin

from hta_classes import BASE_PATH, HTA_Assignment, asgn_data

raise NotImplementedError('This needs updating')

group_dir = pjoin(BASE_PATH, 'ta/grading/data/projects')

group_projs = []
for key in asgn_data['assignments']:
    if asgn_data['assignments'][key]['group_asgn']:
        group_projs.append(key)

if not group_projs:
    print('No projects to check')
    sys.exit(0)

for i, p in enumerate(group_projs):
    print('%s. %s' % (i + 1, p))

print('Which project would you like to check?')
i = int(input('> '))
check_p = group_projs[i - 1]

asgn = HTA_Assignment(check_p)

# currently assumes one question assignment
q = asgn.questions[0]
for handin in q.handins:
    login = asgn.id_to_login(handin.id)
    grader = handin.grader
    if not handin.complete:
        if not handin.extracted:
            '%s has not extracted %s\'s handin' % (grader, login)
        else:
            '%s is still grading %s\'s handin' % (grader, login)
